// Generated by jextract

package com.commons.project;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor printc$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle printc$MH = RuntimeHelper.downcallHandle(
        "printc",
        constants$0.printc$FUNC
    );
}


